# Generated by Django 3.0.2 on 2020-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_code', models.CharField(max_length=100)),
                ('stock_price', models.IntegerField()),
                ('runtime_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
