# Generated by Django 3.0.2 on 2020-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='runtime_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='stock_price',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
