# Generated by Django 3.0.2 on 2020-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200129_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='company_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
